name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        run: |
          docker info
          docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
          docker pull $CI_REGISTRY_IMAGE:latest || true
          docker build --cache-from $CI_REGISTRY_IMAGE:latest --build-arg GIT_COMMIT=$GITHUB_SHA --tag $CI_REGISTRY_IMAGE:latest .
          docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$GITHUB_SHA
          docker push $CI_REGISTRY_IMAGE:$GITHUB_SHA
          docker push $CI_REGISTRY_IMAGE:latest
        env:
          CI_REGISTRY_IMAGE: modbay/job-runner
          CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
          CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Test
        run: |
          echo TODO
      - name: Deploy with Helm
        run: |
          docker run \
            -e CI_COMMIT_SHA=$GITHUB_SHA \
            -e KUBE_CONFIG_BASE64="$KUBE_CONFIG_BASE64" \
            -v $PWD:/code \
            --entrypoint /code/scripts/ci/helm_deploy.sh \
            lwolf/helm-kubectl-docker:v1.18.5-v3.2.4
        env:
          KUBE_CONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64 }}
